/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view_client;

import com.mysql.fabric.xmlrpc.Client;
import doiTuong.user;
import java.net.Socket;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
//
import java.io.IOException;
import java.net.Socket;
import java.io.*;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import jdk.nashorn.internal.ir.BreakNode;
import model.kiemTraDangKi;
import model.kiemTraDangNhap;
import static view_client.OTP.client;

/**
 *
 * @author thao
 */
public class OTP extends javax.swing.JFrame {
    
    public static Socket client;
    public static int flagx = 0;

    /**
     * Creates new form OTP
     */
    public OTP() {
        initComponents();
        //tat thu phong
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        DangNhapDangKi = new javax.swing.JPanel();
        Dieukhien = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        NoiDung = new javax.swing.JPanel();
        DangNhap = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        nhoThongTin = new javax.swing.JCheckBox();
        xacnhanDangNhap = new javax.swing.JButton();
        DangKi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFHoTen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFNgaySinh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFUser = new javax.swing.JTextField();
        jTextFPassword = new javax.swing.JTextField();
        jTextFNhapLaiPassword = new javax.swing.JTextField();
        jTextFEmail = new javax.swing.JTextField();
        jTextFSoDT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnDangKi = new javax.swing.JButton();
        NguyenLi = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        ManHinhGiaoDich = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        NoiDungLayMa = new javax.swing.JPanel();
        TieuDe = new javax.swing.JPanel();
        btnBatDauLayMa = new javax.swing.JButton();
        NoiDungLay = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtThoiGianGiaoDich = new javax.swing.JLabel();
        JTextFMaOTP = new javax.swing.JTextField();
        btnXacNhanMaOTP = new javax.swing.JButton();
        txtTrangThaiKey = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        Dieukhien.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/nenweb.png")))); // NOI18N

        jButton1.setText("Đăng Nhập");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Đăng kí");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Thoát");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Nguyên lí");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DieukhienLayout = new javax.swing.GroupLayout(Dieukhien);
        Dieukhien.setLayout(DieukhienLayout);
        DieukhienLayout.setHorizontalGroup(
            DieukhienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DieukhienLayout.setVerticalGroup(
            DieukhienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DieukhienLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NoiDung.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/nenweb.png")))); // NOI18N
        NoiDung.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Chào mừng bạn đến OTP");

        jLabel2.setText("User");

        jLabel3.setText("Password");

        password.setToolTipText("Nhập thông tin");
        password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        nhoThongTin.setText("Nhớ thông tin");

        xacnhanDangNhap.setText("Xác nhận");
        xacnhanDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xacnhanDangNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DangNhapLayout = new javax.swing.GroupLayout(DangNhap);
        DangNhap.setLayout(DangNhapLayout);
        DangNhapLayout.setHorizontalGroup(
            DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangNhapLayout.createSequentialGroup()
                .addGroup(DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DangNhapLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nhoThongTin)
                            .addComponent(xacnhanDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DangNhapLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(72, 72, 72)
                        .addGroup(DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        DangNhapLayout.setVerticalGroup(
            DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangNhapLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(xacnhanDangNhap)
                .addGap(54, 54, 54)
                .addComponent(nhoThongTin)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        NoiDung.add(DangNhap, "card2");

        jLabel4.setText("Nhap thong tin cua ban");

        jLabel5.setText("HoTen");

        jTextFHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFHoTenActionPerformed(evt);
            }
        });
        jTextFHoTen.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextFHoTenPropertyChange(evt);
            }
        });

        jLabel6.setText("Ngay sinh");

        jLabel7.setText("User");

        jTextFNhapLaiPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFNhapLaiPasswordActionPerformed(evt);
            }
        });

        jTextFSoDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFSoDTActionPerformed(evt);
            }
        });

        jLabel8.setText("Passsword");

        jLabel9.setText("NhapLaiPass");

        jLabel10.setText("Email");

        jLabel11.setText("So dien thoai");

        btnDangKi.setText("Dang ki");
        btnDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DangKiLayout = new javax.swing.GroupLayout(DangKi);
        DangKi.setLayout(DangKiLayout);
        DangKiLayout.setHorizontalGroup(
            DangKiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangKiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DangKiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DangKiLayout.createSequentialGroup()
                        .addGroup(DangKiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(58, 58, 58)
                        .addGroup(DangKiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFUser, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFNhapLaiPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5))
                .addContainerGap(203, Short.MAX_VALUE))
            .addGroup(DangKiLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(btnDangKi)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DangKiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        DangKiLayout.setVerticalGroup(
            DangKiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangKiLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGap(46, 46, 46)
                .addGroup(DangKiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(DangKiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(DangKiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(DangKiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DangKiLayout.createSequentialGroup()
                        .addGroup(DangKiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(30, 30, 30)
                        .addGroup(DangKiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFNhapLaiPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(35, 35, 35)
                        .addGroup(DangKiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(50, 50, 50))
                    .addGroup(DangKiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jTextFSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(btnDangKi)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        NoiDung.add(DangKi, "card3");

        NguyenLi.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/trang_otp.png"))); // NOI18N

        javax.swing.GroupLayout NguyenLiLayout = new javax.swing.GroupLayout(NguyenLi);
        NguyenLi.setLayout(NguyenLiLayout);
        NguyenLiLayout.setHorizontalGroup(
            NguyenLiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NguyenLiLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(19, 19, 19))
        );
        NguyenLiLayout.setVerticalGroup(
            NguyenLiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NguyenLiLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        NoiDung.add(NguyenLi, "card4");

        javax.swing.GroupLayout DangNhapDangKiLayout = new javax.swing.GroupLayout(DangNhapDangKi);
        DangNhapDangKi.setLayout(DangNhapDangKiLayout);
        DangNhapDangKiLayout.setHorizontalGroup(
            DangNhapDangKiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangNhapDangKiLayout.createSequentialGroup()
                .addComponent(Dieukhien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(NoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DangNhapDangKiLayout.setVerticalGroup(
            DangNhapDangKiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dieukhien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(DangNhapDangKi, "card2");

        ManHinhGiaoDich.setBackground(new java.awt.Color(0, 139, 0));

        jPanel1.setBackground(new java.awt.Color(0, 205, 0));

        jButton5.setText("quay lai");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnThoat.setText("thoat");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel12.setText("Chuc quy khach giao dich thanh cong");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addGap(145, 145, 145)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThoat)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jLabel12))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThoat)
                .addContainerGap())
        );

        NoiDungLayMa.setLayout(new java.awt.CardLayout());

        TieuDe.setBackground(new java.awt.Color(0, 153, 51));

        btnBatDauLayMa.setText("bat dau lay ma");
        btnBatDauLayMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatDauLayMaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TieuDeLayout = new javax.swing.GroupLayout(TieuDe);
        TieuDe.setLayout(TieuDeLayout);
        TieuDeLayout.setHorizontalGroup(
            TieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TieuDeLayout.createSequentialGroup()
                .addContainerGap(264, Short.MAX_VALUE)
                .addComponent(btnBatDauLayMa, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
        );
        TieuDeLayout.setVerticalGroup(
            TieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TieuDeLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(btnBatDauLayMa)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        NoiDungLayMa.add(TieuDe, "card2");

        NoiDungLay.setBackground(new java.awt.Color(0, 153, 51));

        jLabel13.setText("nhap ma OTP");

        txtThoiGianGiaoDich.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtThoiGianGiaoDich.setText("00:00");

        JTextFMaOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFMaOTPActionPerformed(evt);
            }
        });

        btnXacNhanMaOTP.setText("Xac nhan");
        btnXacNhanMaOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanMaOTPActionPerformed(evt);
            }
        });

        txtTrangThaiKey.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        javax.swing.GroupLayout NoiDungLayLayout = new javax.swing.GroupLayout(NoiDungLay);
        NoiDungLay.setLayout(NoiDungLayLayout);
        NoiDungLayLayout.setHorizontalGroup(
            NoiDungLayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NoiDungLayLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NoiDungLayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NoiDungLayLayout.createSequentialGroup()
                        .addComponent(txtThoiGianGiaoDich, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(253, 253, 253))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NoiDungLayLayout.createSequentialGroup()
                        .addComponent(btnXacNhanMaOTP)
                        .addGap(243, 243, 243))))
            .addGroup(NoiDungLayLayout.createSequentialGroup()
                .addGroup(NoiDungLayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NoiDungLayLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel13)
                        .addGap(56, 56, 56)
                        .addComponent(JTextFMaOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NoiDungLayLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(txtTrangThaiKey, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        NoiDungLayLayout.setVerticalGroup(
            NoiDungLayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoiDungLayLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(txtThoiGianGiaoDich, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addGroup(NoiDungLayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(JTextFMaOTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(btnXacNhanMaOTP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(txtTrangThaiKey, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        NoiDungLayMa.add(NoiDungLay, "card3");

        javax.swing.GroupLayout ManHinhGiaoDichLayout = new javax.swing.GroupLayout(ManHinhGiaoDich);
        ManHinhGiaoDich.setLayout(ManHinhGiaoDichLayout);
        ManHinhGiaoDichLayout.setHorizontalGroup(
            ManHinhGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NoiDungLayMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ManHinhGiaoDichLayout.setVerticalGroup(
            ManHinhGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManHinhGiaoDichLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NoiDungLayMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(ManHinhGiaoDich, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //remove
        NoiDung.removeAll();
        NoiDung.repaint();
        NoiDung.revalidate();
        //add
        NoiDung.add(DangNhap);
        NoiDung.repaint();
        NoiDung.revalidate();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //remove
        NoiDung.removeAll();
        NoiDung.repaint();
        NoiDung.revalidate();
        //add
        NoiDung.add(DangKi);
        NoiDung.repaint();
        NoiDung.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void xacnhanDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xacnhanDangNhapActionPerformed
        try {
            // nut dang nhap
            PrintStream ps = new PrintStream(client.getOutputStream());
            kiemTraDangNhap x = new kiemTraDangNhap(user.getText().toString(), password.getText().toString());
            if (x.kiemTraRong()) {
                ps.println(0 + user.getText().toString());
                ps.println(0 + password.getText().toString());
            }
        } catch (IOException ex) {
            Logger.getLogger(OTP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_xacnhanDangNhapActionPerformed

    private void btnDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKiActionPerformed
        try {
            // TODO add your handling code here:
            PrintStream ps = new PrintStream(client.getOutputStream());
            user user1 = new user(jTextFHoTen.getText().toString(), jTextFNgaySinh.getText().toString(), jTextFUser.getText().toString(), jTextFPassword.getText().toString(), jTextFNhapLaiPassword.getText().toString(), jTextFEmail.getText().toString(), Integer.parseInt(jTextFSoDT.getText().toString().trim()));
            kiemTraDangKi x = new kiemTraDangKi(user1);
            if (x.kiemTraRong()) {
                if (user1.getPassword().equals(user1.getLaiPassword())) {
                    
                    ps.println(1 + user1.getHoten());
                    ps.println(1 + user1.getNgaySinh());
                    ps.println(1 + user1.getUser());
                    ps.println(1 + user1.getPassword());
                    ps.println(1 + user1.getLaiPassword());
                    ps.println(1 + user1.getEmail());
                    ps.println(1 + user1.getSoDT());
                } else {
                    JOptionPane.showMessageDialog(ManHinhGiaoDich, "password khong trùng nhau!");
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(OTP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDangKiActionPerformed

    private void jTextFHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFHoTenActionPerformed

    private void jTextFNhapLaiPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFNhapLaiPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFNhapLaiPasswordActionPerformed

    private void jTextFSoDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFSoDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFSoDTActionPerformed
    

    private void jTextFHoTenPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextFHoTenPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFHoTenPropertyChange

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void btnBatDauLayMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatDauLayMaActionPerformed
        try {
            NoiDungLayMa.removeAll();
            NoiDungLayMa.repaint();
            NoiDungLayMa.revalidate();
            //add
            NoiDungLayMa.add(NoiDungLay);
            NoiDungLayMa.repaint();
            NoiDungLayMa.revalidate();
            PrintStream ps = new PrintStream(client.getOutputStream());
            ps.println("Bat dau");
            
        } catch (IOException ex) {
            Logger.getLogger(OTP.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnBatDauLayMaActionPerformed

    private void btnXacNhanMaOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanMaOTPActionPerformed
        try {
            // TODO add your handling code here:
            PrintStream ps = new PrintStream(client.getOutputStream());
            if (JTextFMaOTP.getText().toString().length() > 7 && JTextFMaOTP.getText().toString().length() < 11) {
                ps.println(JTextFMaOTP.getText().toString());
            } else {
                JOptionPane.showMessageDialog(NoiDungLay, "yêu cầu nhập đúng 9 chữ số!");
            }
        } catch (IOException ex) {
            System.out.println("sai nut xac nhan ma otp(619)");
            Logger.getLogger(OTP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXacNhanMaOTPActionPerformed

    private void JTextFMaOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFMaOTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFMaOTPActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            PrintStream ps = new PrintStream(client.getOutputStream());
            ps.println("dang xuat");
            ManHinhGiaoDich.setVisible(false);
            DangNhapDangKi.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(OTP.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        thoat();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        //remove
//        NoiDung.removeAll();
//        NoiDung.repaint();
//        NoiDung.revalidate();
//        //add
//        NoiDung.add(NguyenLi);
//        NoiDung.repaint();
//        NoiDung.revalidate();
        show s = new show();
        s.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed
    public void thoat() {
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        int kq = JOptionPane.showConfirmDialog(null, "ban co muon thoat ?", "Congfig", JOptionPane.YES_NO_OPTION);
        if (kq == 0) {
            System.exit(0);
        }
    }
    
    public static final void tiepTuc() {
        int kq = JOptionPane.showConfirmDialog(null, "key hợp lệ, bạn có muốn tiếp tục không?", "Thông tin", JOptionPane.YES_NO_OPTION);
        if (kq == 0) {
            NoiDungLayMa.removeAll();
            NoiDungLayMa.repaint();
            NoiDungLayMa.revalidate();
            //add
            NoiDungLayMa.add(TieuDe);
            NoiDungLayMa.repaint();
            NoiDungLayMa.revalidate();
            flagx = 0;
        }else{
            flagx = 1;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new OTP().setVisible(true);
            }
        });
        client = new Socket("localhost", 8888);
        new Thread(new Runnable() {
            @Override
            
            public void run() {
                while (true) {
                    try {
                        BufferedReader br = new BufferedReader(new InputStreamReader(client.getInputStream()));
                        
                        String k = br.readLine().trim();

//                        
                        System.out.println("ket qua: " + k);
//                             String[] x=k.split("\\s");
//                        
                        //                 int l=Integer.parseInt(x[0]);
                        if (k.equals("Thanh cong")) {
                            
                            DangNhapDangKi.setVisible(false);
                            ManHinhGiaoDich.setVisible(true);
                            //
                            NoiDungLayMa.removeAll();
                            NoiDungLayMa.repaint();
                            NoiDungLayMa.revalidate();
                            //add
                            NoiDungLayMa.add(TieuDe);
                            NoiDungLayMa.repaint();
                            NoiDungLayMa.revalidate();
                            flagx = 0;
                        } else if (k.equals("Key hop le")) {
                            
                            tiepTuc();
                            
                        } else if (k.equals("sai user hoac passsword!")) {
                            JOptionPane.showMessageDialog(DangNhapDangKi, "sai user hoac passsword!");
                        } else if (k.equals("qua thoi gian!")) {
                            flagx = 1;
                            JOptionPane.showMessageDialog(NoiDungLayMa, "qua thoi gian nhap!");
                            
                        } else if (k.equals("dang ki ko thanh cong!")) {
                            JOptionPane.showMessageDialog(DangNhapDangKi, "Ten user da duoc dung, moi chon ten khac!");
                            
                        } else if (k.equals("key không đúng mời nhập lại")) {
                            JOptionPane.showMessageDialog(NoiDungLayMa, "Key không đúng!");
                            flagx = 1;
                            
                        } else if (k.equals("da dang xuat")) {
                            flagx = 1;
                        } else if (k.equals("1 phut")) {
                            new Thread(new Runnable() {
                                @Override
                                public void run() {
                                    
                                    int dem = 60;
                                    int phut = 1;
                                    int giay = 0;
                                    String chuoi = "";
                                    while (true) {
                                        if (flagx == 1) {
                                            break;
                                        }
                                        if (giay > 9) {
                                            chuoi = "0" + phut + ":" + giay;
                                        } else {
                                            chuoi = "0" + phut + ":0" + giay;
                                        }
                                        
                                        txtThoiGianGiaoDich.setText(chuoi);
                                        dem--;
                                        phut = 0;
                                        giay = dem;
                                        
                                        if (dem == 0) {
                                            chuoi = "0" + phut + ":0" + giay;
                                            txtThoiGianGiaoDich.setText(chuoi);
                                            JOptionPane.showMessageDialog(ManHinhGiaoDich, "Hết thời gian nhập!");
//                                            int g=JOptionPane.YES_NO_OPTION;
//                                            int gg=JOptionPane.showConfirmDialog(ManHinhGiaoDich, "sss","sssss",g);
//                                            if(gg==0){
//                                                System.out.println(".run()");
//                                            }else{
//                                                System.out.println(".run()gg");
//                                            }
                                            
                                            break;
                                        }
                                        try {
                                            Thread.sleep(1000);
                                        } catch (InterruptedException ex) {
                                            Logger.getLogger(OTP.class.getName()).log(Level.SEVERE, null, ex);
                                        }
                                        
                                    }
                                    
                                }
                            }).start();
                        }
                    } catch (IOException ex) {
                    }
                }
                
            }
        }).start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DangKi;
    private javax.swing.JPanel DangNhap;
    public static javax.swing.JPanel DangNhapDangKi;
    private javax.swing.JPanel Dieukhien;
    public static javax.swing.JTextField JTextFMaOTP;
    public static javax.swing.JPanel ManHinhGiaoDich;
    private javax.swing.JPanel NguyenLi;
    private javax.swing.JPanel NoiDung;
    public static javax.swing.JPanel NoiDungLay;
    public static javax.swing.JPanel NoiDungLayMa;
    public static javax.swing.JPanel TieuDe;
    public static javax.swing.JButton btnBatDauLayMa;
    public javax.swing.JButton btnDangKi;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXacNhanMaOTP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextFEmail;
    public javax.swing.JTextField jTextFHoTen;
    public javax.swing.JTextField jTextFNgaySinh;
    public javax.swing.JTextField jTextFNhapLaiPassword;
    public javax.swing.JTextField jTextFPassword;
    public javax.swing.JTextField jTextFSoDT;
    public javax.swing.JTextField jTextFUser;
    public static javax.swing.JCheckBox nhoThongTin;
    public javax.swing.JTextField password;
    public static javax.swing.JLabel txtThoiGianGiaoDich;
    public static javax.swing.JLabel txtTrangThaiKey;
    public javax.swing.JTextField user;
    public javax.swing.JButton xacnhanDangNhap;
    // End of variables declaration//GEN-END:variables
}
